---


- name: Install mysql client and server
  yum:
    pkg={{ item }}
    state=latest
  with_items:
    - mysql
    - mysql-server
  register: installed

- name: Start mysqld server
  service:
    name=mysqld
    state=started
    enabled=yes
  when: installed.changed